export const champions = [
    { name: "Aatrox", image: "Images/champions/Aatrox.jpeg", hasSixStars: true },
    {name:"Ambessa", image: "Images/champions/Ambessa.jpg", hasSixStars: true},
    { name: "Akshan", image: "Images/champions/Akshan.jpeg", hasSixStars: true },
    { name: "Ahri", image: "Images/champions/Ahri.jpeg", hasSixStars: true },
    { name: "Annie", image: "Images/champions/Annie.jpeg", hasSixStars: false },
    { name: "Ashe", image: "Images/champions/Ashe.jpeg", hasSixStars: true },
    { name: "Bard", image: "Images/champions/Bard.jpeg", hasSixStars: false },
    { name: "Caitlyn", image: "Images/champions/Caitlyn.jpeg", hasSixStars: true },
    { name: "Darius", image: "Images/champions/Darius.jpeg", hasSixStars: true },
    { name: "Diana", image: "Images/champions/Diana.jpeg", hasSixStars: false },
    { name: "Ekko", image: "Images/champions/Ekko.jpeg", hasSixStars: true },
    { name: "Elder Dragon", image: "Images/champions/Elder.jpeg", hasSixStars: true },
    { name: "Elise", image: "Images/champions/Elise.jpeg", hasSixStars: false },
    { name: "Evelynn", image: "Images/champions/Evelynn.jpeg", hasSixStars: true },
    { name: "Fiddlesticks", image: "Images/champions/Fiddlesticks.jpeg", hasSixStars: true },
    { name: "Garen", image: "Images/champions/Garen.jpeg", hasSixStars: false },
    { name: "Gnar", image: "Images/champions/Gnar.jpeg", hasSixStars: false },
    { name: "Gwen", image: "Images/champions/Gwen.jpeg", hasSixStars: true },
    { name: "Heimerdinger", image: "Images/champions/Heimerdinger.jpeg", hasSixStars: true },
    { name: "Illaoi", image: "Images/champions/Illaoi.jpeg", hasSixStars: false },
    { name: "Jack", image: "Images/champions/Jack.jpeg", hasSixStars: false },
    { name: "Janna", image: "Images/champions/Janna.jpeg", hasSixStars: false },
    { name: "Jax", image: "Images/champions/Jax.jpeg", hasSixStars: false },
    { name: "Jayce", image: "Images/champions/Jayce.jpeg", hasSixStars: true },
    { name: "Jhin", image: "Images/champions/Jhin.jpeg", hasSixStars: true },
    { name: "Jinx", image: "Images/champions/Jinx.jpeg", hasSixStars: true },
    { name: "Kai'Sa", image: "Images/champions/KaiSa.jpeg", hasSixStars: true },
    { name: "Kayle", image: "Images/champions/Kayle.jpeg", hasSixStars: true },
    { name: "Kayn", image: "Images/champions/Kayn.jpeg", hasSixStars: false },
    { name: "Kindred", image: "Images/champions/Kindred.jpeg", hasSixStars: false },
    { name: "LeBlanc", image: "Images/champions/LeBlanc.jpeg", hasSixStars: false },
    { name: "Lee Sin", image: "Images/champions/LeeSin.jpeg", hasSixStars: false },
    { name: "Leona", image: "Images/champions/Leona.jpeg", hasSixStars: true },
    { name: "Lillia", image: "Images/champions/Lillia.jpeg", hasSixStars: true },
    { name: "Lux", image: "Images/champions/Lux.jpeg", hasSixStars: true },
    { name: "Lux: Illuminated", image: "Images/champions/LuxI.jpeg", hasSixStars: true },
    { name: "Master Yi", image: "Images/champions/MasterYi.jpeg", hasSixStars: false },
    { name: "Miss Fortune", image: "Images/champions/MissFortune.jpeg", hasSixStars: true },
    { name: "Mordekaiser", image: "Images/champions/Mordekaiser.jpeg", hasSixStars: false },
    { name: "Morgana", image: "Images/champions/Morgana.jpeg", hasSixStars: true },
    { name: "Nami", image: "Images/champions/Nami.jpeg", hasSixStars: false },
    { name: "Nasus", image: "Images/champions/Nasus.jpeg", hasSixStars: true },
    { name: "Nautilus", image: "Images/champions/Nautilus.jpeg", hasSixStars: true },
    { name: "Neeko", image: "Images/champions/Neeko.jpeg", hasSixStars: true },
    { name: "Nidalee", image: "Images/champions/Nidalee.jpeg", hasSixStars: false },
    { name: "Nilah", image: "Images/champions/Nilah.jpeg", hasSixStars: false },
    { name: "Norra", image: "Images/champions/Norra.jpeg", hasSixStars: true },
    { name: "Ornn", image: "Images/champions/Ornn.jpeg", hasSixStars: false },
    { name: "Pyke", image: "Images/champions/Pyke.jpeg", hasSixStars: true },
    { name: "Samira", image: "Images/champions/Samira.jpeg", hasSixStars: true },
    { name: "Sett", image: "Images/champions/Sett.jpeg", hasSixStars: false },
    { name: "Swain", image: "Images/champions/Swain.jpeg", hasSixStars: true },
    { name: "Tahm Kench", image: "Images/champions/TahmKench.jpeg", hasSixStars: false },
    { name: "Taliyah", image: "Images/champions/Taliyah.jpeg", hasSixStars: true },
    { name: "Teemo", image: "Images/champions/Teemo.jpeg", hasSixStars: false },
    { name: "The Poro King", image: "Images/champions/ThePoroKing.jpeg", hasSixStars: false },
    { name: "Thresh", image: "Images/champions/Thresh.jpeg", hasSixStars: false },
    { name: "Tryndamere", image: "Images/champions/Tryndamere.jpeg", hasSixStars: true },
    { name: "Varus", image: "Images/champions/Varus.jpeg", hasSixStars: false },
    { name: "Vayne", image: "Images/champions/Vayne.jpeg", hasSixStars: true },
    { name: "Veigar", image: "Images/champions/Veigar.jpeg", hasSixStars: false },
    { name: "Vex", image: "Images/champions/Vex.jpeg", hasSixStars: true },
    { name: "Vi", image: "Images/champions/Vi.jpeg", hasSixStars: true },
    { name: "Viego", image: "Images/champions/Viego.jpeg", hasSixStars: true },
    { name: "Volibear", image: "Images/champions/Volibear.jpeg", hasSixStars: true },
    { name: "Yasuo", image: "Images/champions/Yasuo.jpeg", hasSixStars: true },
    { name: "Yummi", image: "Images/champions/Yummi.jpeg", hasSixStars: true },
    { name: "Viktor", image: "Images/champions/Viktor.jpeg", hasSixStars: true },
    { name: "Warwick", image: "Images/champions/Warwick.jpeg", hasSixStars: true },
    { name: "Aurelion Sol", image: "Images/champions/AurelionSol.jpeg", hasSixStars: false }
   ];