export const adventures = [
    { name: "The Swift Scout", image: "Images/champions/Teemo.jpeg", stars: 0, type: "normal" },
    { name: "The Bounty Hunter", image: "Images/champions/MissFortune.jpeg", stars: 0.5, type: "normal" },
    { name: "The Might of Demacia", image: "Images/champions/Lux.jpeg", stars: 1, type: "normal" },
    { name: "The Fae Sorceress", image: "Images/champions/Lulu.jpeg", stars: 1, type: "normal" },
    { name: "The Wrath of Zaun", image: "Images/champions/Warwick.jpeg", stars: 1, type: "normal" },
    { name: "The Saltwater Scourge", image: "Images/champions/Gankplank.jpeg", stars: 1.5, type: "normal" },
    { name: "The Prodigal Explorer", image: "Images/champions/Ezreal.jpeg", stars: 1.5, type: "normal" },
    { name: "The Master of Shadows", image: "Images/champions/Zed.jpeg", stars: 2, type: "normal" },
    { name: "The Titan of the Depths", image: "Images/champions/Nautilus.jpeg", stars: 2, type: "normal" },
    { name: "The Hand of Noxus", image: "Images/champions/Darius.jpeg", stars: 2, type: "normal" },
    { name: "The Machine Herald", image: "Images/champions/Viktor.jpeg", stars: 2.5, type: "normal" },
    { name: "The Glorious Executioner", image: "Images/champions/Draven.jpeg", stars: 2.5, type: "normal" },
    { name: "Daughter of the Void", image: "Images/champions/KaiSa.jpeg", stars: 3, type: "normal" },
    { name: "The Collector of Souls", image: "Images/champions/Thresh.jpeg", stars: 3, type: "normal" },
    { name: "The Dragonsire", image: "Images/champions/Elder.jpeg", stars: 3, type: "normal" },
    { name: "The Colossus", image: "Images/champions/Galio.jpeg", stars: 3.5, type: "normal" },
    { name: "The Ancient Fear", image: "Images/champions/Fiddlesticks.jpeg", stars: 3.5, type: "normal" },
    { name: "The Star Forger", image: "Images/champions/AurelionSol.jpeg", stars: 4, type: "normal" },
    { name: "The Unforgiven", image: "Images/champions/Yasuo.jpeg", stars: 4.5, type: "normal" },
    { name: "The Frost Witch", image: "Images/champions/Lissandra.jpeg", stars: 5, type: "normal" },
    { name: "The Noxian Grand General", image: "Images/champions/Swain.jpeg", stars: 5, type: "normal" },
    { name: "Starlight Portal", image: "Images/champions/Weekly.jpeg", stars: 1, type: "normal" },
    { name: "Shadow Portal", image: "Images/champions/Weekly.jpeg", stars: 2, type: "normal" },
    { name: "Dark Star Portal", image: "Images/champions/Weekly.jpeg", stars: 3, type: "normal" },
    { name: "The Tidal Trickster", image: "Images/champions/Fizz.jpeg", stars: 4.5, type: "Nightmare" },
    { name: "The Ruined King", image: "Images/champions/Viego.jpeg", stars: 5, type: "Nightmare" },
    { name: "The Ancient Fear", image: "Images/champions/Fiddlesticks.jpeg", stars: 6.5, type: "Nightmare" },
    { name: "Fear Portal", image: "Images/champions/Weekly.jpeg", stars: 4.5, type: "Nightmare" },
    { name: "Terror Portal", image: "Images/champions/Weekly.jpeg", stars: 5.5, type: "Nightmare" },
    { name: "Nightmare Portal", image: "Images/champions/Weekly.jpeg", stars: 6.5, type: "Nightmare" },
    { name: "The Boss", image: "Images/champions/Sett.jpeg", stars: 2, type: "Event" },
    { name: "The Iron Revenant", image: "Images/champions/Mordekaiser.jpeg", stars: 3, type: "Event" },
    { name: "The Titan of the Depths", image: "Images/champions/Nautilus.jpeg", stars: 4, type: "Event" },
    { name: "The Relentless Storm", image: "Images/champions/Volibear.jpeg", stars: 5, type: "Event" },
    { name: "The Dragonsire", image: "Images/champions/Elder.jpeg", stars: 6, type: "Event" }
];