export const relics = [
    { name: "Protectors of Demacia", image: "Images/relics/protectors.webp", rarity: "epic" },
    { name: "Shield of Daybreak", image: "Images/relics/shield_L.webp", rarity: "epic" },
    { name: "Whisper", image: "Images/relics/Whisper.webp", rarity: "epic" },
    { name: "Scoundrel Hunter", image: "Images/relics/Scoundrel_Hunter.webp", rarity: "epic" },
    { name: "Armordillo Shell", image: "Images/relics/armodillo.webp", rarity: "common" },
    { name: "Banshee's Veil", image: "Images/relics/banshee.webp", rarity: "common" },
    { name: "Dreams Of Yordles", image: "Images/relics/dream.webp", rarity: "common" },
    { name: "Everfrost", image: "Images/relics/Everfrost.webp", rarity: "common" },
    { name: "Guinsoo's Rageblade", image: "Images/relics/Guinsoo's.webp", rarity: "common" },
    { name: "Lost Chapter", image: "Images/relics/Lost_Chapter.webp", rarity: "common" },
    { name: "Ravenous Hydra", image: "Images/relics/Ravenous_Hydra.webp", rarity: "common" },
    { name: "Soul Spear", image: "Images/relics/Soul_Spear.webp", rarity: "common" },
    { name: "Stormrazor", image: "Images/relics/Stormrazor.webp", rarity: "common" },
    { name: "The Chameleon's Necklace", image: "Images/relics/The_Chameleon's Necklace.webp", rarity: "common" },
    { name: "The Grand Duelist's Blade", image: "Images/relics/The_Grand_Duelist's_Blade.webp", rarity: "common" },
    { name: "The Starchild's Staff", image: "Images/relics/The_Starchild's_Staff.webp", rarity: "common" },
    { name: "The Troll King's Crusher", image: "Images/relics/The_Troll_King's_Crusher.webp", rarity: "common" },
    { name: "True Ice Flail", image: "Images/relics/True_Ice_Flail.webp", rarity: "common" },
    { name: "Warmog's Armor", image: "Images/relics/Warmog's_Armor.webp", rarity: "common" },
    { name: "Z-Drive Prototype", image: "Images/relics/Z-Drive.webp", rarity: "common" },
    { name: "Arcane Comet", image: "Images/relics/Arcane_Comet.webp", rarity: "rare" },
    { name: "Archangel's Staff", image: "Images/relics/Archangel's_Staff.webp", rarity: "rare" },
    { name: "Caulfield's Warhammer", image: "Images/relics/Caulfield's_Warhammer.webp", rarity: "rare" },
    { name: "Chemtech Duplicator", image: "Images/relics/Chemtech_Duplicator.webp", rarity: "rare" },
    { name: "Condenser", image: "Images/relics/Condenser.webp", rarity: "rare" },
    { name: "Corrupted Star Fragment", image: "Images/relics/Corrupted_Star_Fragment.webp", rarity: "rare" },
    { name: "Crownguard Inheritance", image: "Images/relics/Crownguard_Inheritance.webp", rarity: "rare" },
    { name: "Dreadway Chase Gun", image: "Images/relics/Dreadway_Chase_Gun.webp", rarity: "rare" },
    { name: "Galeforce", image: "Images/relics/Galeforce.webp", rarity: "rare" },
    { name: "Golden Spatula", image: "Images/relics/Golden_Spatula.webp", rarity: "rare" },
    { name: "Greenglade Shadeleaf", image: "Images/relics/Greenglade_Shadeleaf.webp", rarity: "rare" },
    { name: "Guardian Angel", image: "Images/relics/Guardian_Angel.webp", rarity: "rare" },
    { name: "Guardian's Orb", image: "Images/relics/Guardian's_Orb.webp", rarity: "rare" },
    { name: "Guardian's Trinket", image: "Images/relics/Guardian's_Trinket.webp", rarity: "rare" },
    { name: "Heart of Gold", image: "Images/relics/Heart_of_Gold.webp", rarity: "rare" },
    { name: "Hymn of Valor", image: "Images/relics/Hymn_of_Valor.webp", rarity: "rare" },
    { name: "Jaurim's Fist", image: "Images/relics/Jaurim's_Fist.webp", rarity: "rare" },
    { name: "Laurent Bladerack", image: "Images/relics/Laurent_Bladerack.webp", rarity: "rare" },
    { name: "Luden's Tempest", image: "Images/relics/Luden's_Tempest.webp", rarity: "rare" },
    { name: "Luminous Orb", image: "Images/relics/Luminous_Orb.webp", rarity: "rare" },
    { name: "Riptide Battery", image: "Images/relics/Riptide_Battery.webp", rarity: "rare" },
    { name: "Stalker's Blade", image: "Images/relics/Stalker's_Blade.webp", rarity: "rare" },
    { name: "Star Gem", image: "Images/relics/Star_Gem.webp", rarity: "rare" },
    { name: "Succubus's Brand", image: "Images/relics/Succubus's_Brand.webp", rarity: "rare" },
    { name: "Tempest Blade", image: "Images/relics/Tempest_Blade.webp", rarity: "rare" },
    { name: "The Berserker's Buckle", image: "Images/relics/The_Berserker's_Bukle.webp", rarity: "rare" },
    { name: "The Bounty Hunter's Renown", image: "Images/relics/The_Bounty_Hunter's_Renown.webp", rarity: "rare" },
    { name: "The Card Master's Gambit", image: "Images/relics/The_Card_Master's_Gambit.webp", rarity: "rare" },
    { name: "The Collector", image: "Images/relics/The_Collector.webp", rarity: "rare" },
    { name: "The Curator's Gatebreaker", image: "Images/relics/The_Curator's_Gatebreaker.webp", rarity: "rare" },
    { name: "The Deceiver's Crest", image: "Images/relics/The_Deceiver's_Crest.webp", rarity: "rare" },
    { name: "The Grand General's Counterplan", image: "Images/relics/The_Grand_General's_Counterplan.webp", rarity: "rare" },
    { name: "The Gravedigger's Spade", image: "Images/relics/The_Gravedigger's_Spade.webp", rarity: "rare" },
    { name: "The Loose Cannon's Payload", image: "Images/relics/The_Loose_Cannon's_Payload.webp", rarity: "rare" },
    { name: "The Scourge's Stash", image: "Images/relics/The_Scourge's_Stash.webp", rarity: "rare" },
    { name: "Troll King's Crown", image: "Images/relics/Troll_King's_Crown.webp", rarity: "rare" },
    { name: "Transmogulator", image: "Images/relics/Transmogulator.webp", rarity: "rare" },
    { name: "Turret Plating", image: "Images/relics/Turret_Plating.webp", rarity: "rare" },
    { name: "Utmost Despair", image: "Images/relics/Utmost_Despair.webp", rarity: "rare" },
    { name: "Voidborne Carapace", image: "Images/relics/Voidborne_Carapace.webp", rarity: "rare" },
    { name: "Wicked Harvest", image: "Images/relics/Wicked_Harvest.webp", rarity: "rare" },
    { name: "Wriggle's Lantern", image: "Images/relics/Wriggle's_Lantern.webp", rarity: "rare" },
    { name: "Big Guns", image: "Images/relics/Big_Guns.webp", rarity: "epic" },
    { name: "Black Shield", image: "Images/relics/Black_Shield.webp", rarity: "epic" },
    { name: "Cease and Desist", image: "Images/relics/Cease_and_Desist.webp", rarity: "epic" },
    { name: "Chosen by the Stars", image: "Images/relics/Chosen_By_The_Stars.webp", rarity: "epic" },
    { name: "Deadly Harpoon", image: "Images/relics/Deadly_Harpoon.webp", rarity: "epic" },
    { name: "Death's Foil", image: "Images/relics/Death's_Foil.webp", rarity: "epic" },
    { name: "Defense Spending", image: "Images/relics/Defense_Spending.webp", rarity: "epic" },
    { name: "Disciple of Shadows", image: "Images/relics/Disciple_of_Shadows.webp", rarity: "epic" },
    { name: "Echoing Spirit", image: "Images/relics/Echoing_Spirit.webp", rarity: "epic" },
    { name: "Essence Theft", image: "Images/relics/Essence_Theft.webp", rarity: "epic" },
    { name: "Fear-Cleaving Axe", image: "Images/relics/Fear-Cleaving_Axe.webp", rarity: "epic" },
    { name: "Found Fortune", image: "Images/relics/Found_Fortune.webp", rarity: "epic" },
    { name: "Frozen Tomb", image: "Images/relics/Frozen_Tomb.webp", rarity: "epic" },
    { name: "Full Build", image: "Images/relics/Full_Build.webp", rarity: "epic" },
    { name: "Hextech Rifle", image: "Images/relics/Hextech_Rifle.webp", rarity: "epic" },
    { name: "Hidden Tome", image: "Images/relics/Hidden_Tome.webp", rarity: "epic" },
    { name: "Icon of Valhir", image: "Images/relics/Icon_of_Valhir.webp", rarity: "epic" },
    { name: "Jayce's Hextech Battery", image: "Images/relics/Jayce's_Hextech_Battery.webp", rarity: "epic" },
    { name: "Living Weapon", image: "Images/relics/Living_Weapon.webp", rarity: "epic" },
    { name: "Loaded Dice", image: "Images/relics/Loaded_Dice.webp", rarity: "epic" },
    { name: "Lux's Incandescent Baton", image: "Images/relics/Lux's_Incandescent_Baton.webp", rarity: "epic" },
    { name: "Norra's Portal Accelerator", image: "Images/relics/Norra's_Portal_Accelerator.webp", rarity: "epic" },
    { name: "Oath of the Guardians", image: "Images/relics/Oath_Of_The_Guardians.webp", rarity: "epic" },
    { name: "Packed Powder", image: "Images/relics/Packed_Powder.webp", rarity: "epic" },
    { name: "Portal Pals", image: "Images/relics/Portal_Pals.webp", rarity: "epic" },
    { name: "Secret Technique", image: "Images/relics/Secret_Technique.webp", rarity: "epic" },
    { name: "Shock & Awe", image: "Images/relics/Shock&Awe.webp", rarity: "epic" },
    { name: "Spectral Scissors", image: "Images/relics/Spectral_Scissors.webp", rarity: "epic" },
    { name: "Spellweaver's Symphony", image: "Images/relics/Spellweaver's_Symphony.webp", rarity: "epic" },
    { name: "Spirit of the Buhru", image: "Images/relics/Spirit_Of_The_Buhru.webp", rarity: "epic" },
    { name: "Strength of Stone", image: "Images/relics/Strength_of_Stone.webp", rarity: "epic" },
    { name: "Stacked Deck", image: "Images/relics/Stacked_Deck.webp", rarity: "epic" },
    { name: "Starforged Gauntlets", image: "Images/relics/Starforged_Gauntlets.webp", rarity: "epic" },
    { name: "Swain's Raven Army", image: "Images/relics/Swain's_Raven_Army.webp", rarity: "epic" },
    { name: "The Beast Within", image: "Images/relics/The_Beast_Within.webp", rarity: "epic" },
    { name: "Yasuo's Windblade", image: "Images/relics/Yasuo's_Windblade.webp", rarity: "epic" }
];